server:
  port: 8885


spring:
  elasticsearch:
    jest:
      uris: http://39.106.211.119:9200
  data:
    elasticsearch:
      cluster-nodes: 39.106.211.119:9300
      cluster-name: elasticsearch
  application:
    name: E17search


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://localhost:8001/eureka
  instance:
      instance-id: E17search8885
      prefer-ip-address: true

