server:
  port: 80


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://39.106.211.119:8001/eureka
  instance:
      instance-id: E17portalWeb8881
      prefer-ip-address: true


  #解决变迁必须结束
spring:
  application:
      name: E17portalWeb    #访问路径可以显示IP地址
  thymeleaf:
    mode: LEGACYHTML5



#搜索模块地址
SEARCH_URL: http://39.106.211.119:8885/



logging:
  level: info
  file: /usr/local/e17/log/EPW.log


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000




